version: '3.1'


services:
  app:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
    - db

  db:
    image: postgres
    restart: always
    volumes:
      -web
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: test
