version: '3.1'


services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - TZ=Europe/Kiev

  db:
    image: postgres
    restart: always
    volumes:
      - web:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: test

volumes:
  web:
